var virusData = {
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "id":1,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.411,
               36.10027
            ]
         },
         "properties":{
            "序号Case":3,
            "年龄Age":41,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Tue, 21 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 23 Jan 2010 00:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"李沧区",
            "地址Address":"青岛市市北区马兰花园",
            "信息Info":"1月14日来青探亲，暂住市北区，1月14日出现发热症状，1月19日到医院发热门诊就诊。经省、市两级疾病控制中心检测、专家组评估，于1月23日确诊。追踪排查到密切接触者共7人，已有6人解除医学观察，现有1人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":1
         }
      },
      {
         "type":"Feature",
         "id":2,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.386635,
               36.289375
            ]
         },
         "properties":{
            "序号Case":5,
            "年龄Age":46,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 24 Jan 2010 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 25 Jan 2010 00:00:00 GMT",
            "籍贯_Original":"莱西市",
            "区划_Area_in_Qingdao":"莱西市",
            "地址Address":"青岛城阳兴阳路702号",
            "信息Info":"1月21日从荆门途经武汉来青岛探亲，暂住城阳区，1月23日到医院发热门诊就诊。经市疾控中心核酸检测为阳性，1月25日专家组评估确诊。2月6日治愈出院。追踪排查到密切接触者共82人，已有74人解除医学观察，现有6人正在进行隔离观察，现有疑似2例。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":2
         }
      },
      {
         "type":"Feature",
         "id":3,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.40375,
               36.205753
            ]
         },
         "properties":{
            "序号Case":8,
            "年龄Age":57,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"是",
            "初次就诊时间_Diagnose_Date":"Mon, 25 Jan 2010 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 00:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市李沧区湘潭路街道中南世纪城小区",
            "信息Info":"在武汉工作，1月20日从武汉回青岛探亲，现住李沧区，1月25日到医院发热门诊就诊。经市疾控中心核酸检测为阳性，1月26日专家组评估确诊。追踪排查到密切接触者共28人，已有23人解除医学观察，现有3人正在进行隔离观察，现有疑似2例。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":3
         }
      },
      {
         "type":"Feature",
         "id":4,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.99051,
               36.752445
            ]
         },
         "properties":{
            "序号Case":17,
            "年龄Age":31,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 24 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 29 Jan 2020 00:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市平度市经济开发区前八里庄村",
            "信息Info":"湖北荆州人，常住平度市，系病例18的妻子，1月21日由武汉到达青岛，1月26日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，1月29日上午确诊。追踪排查到密切接触者共38人，已有14人解除医学观察，现有20人正在进行隔离观察，确诊2例，现有疑似2例。（系病例18的妻子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":4
         }
      },
      {
         "type":"Feature",
         "id":5,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.99051,
               36.752445
            ]
         },
         "properties":{
            "序号Case":18,
            "年龄Age":40,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Wed, 29 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 29 Jan 2020 00:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"平度市",
            "地址Address":"青岛市平度市经济开发区前八里庄村",
            "信息Info":"湖北荆州人，常住平度市，系病例17的丈夫，1月29日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，1月29日下午确诊。追踪排查到密切接触者共7人，现有7人正在进行隔离观察。（系病例17的丈夫）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":5
         }
      },
      {
         "type":"Feature",
         "id":6,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.99051,
               36.752445
            ]
         },
         "properties":{
            "序号Case":28,
            "年龄Age":70,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"平度市",
            "区划_Area_in_Qingdao":"平度市",
            "地址Address":"青岛市平度市经济开发区前八里庄村",
            "信息Info":"系病例17的婆婆、病例18的母亲，2月3日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，2月3日下午确诊。追踪排查到密切接触者共4人，现有4人正在进行隔离观察。（系病例17的婆婆、病例18的母亲）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":6
         }
      },
      {
         "type":"Feature",
         "id":7,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.33337,
               36.089954
            ]
         },
         "properties":{
            "序号Case":33,
            "年龄Age":60,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 26 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"市北区",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区普集路17号普集新区小区",
            "信息Info":"系病例27的姑姑、病例32的女儿，1月27日到市北区某医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月4日下午确诊。追踪排查到密切接触者共36人，现有36人正在进行隔离观察。（系病例27的姑姑、病例32的女儿）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":7
         }
      },
      {
         "type":"Feature",
         "id":8,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.4216,
               36.393085
            ]
         },
         "properties":{
            "序号Case":36,
            "年龄Age":50,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区通济街道庄头新村",
            "信息Info":"现住即墨区，系病例25的亲家，与病例25有密切接触，2月4日在密切接触者筛查中经市疾控中心核酸检测为阳性，属无症状感染者。2月5日下午由即墨区某医院确诊。与病例25、病例37的共同密切接触者已进行隔离观察。（系病例25的亲家、病例37的奶奶）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":8
         }
      },
      {
         "type":"Feature",
         "id":9,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.51903,
               36.89497
            ]
         },
         "properties":{
            "序号Case":49,
            "年龄Age":55,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sat, 08 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 08 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"莱西市",
            "地址Address":"青岛市莱西市翡翠城西区",
            "信息Info":"常住莱西市翡翠城西区。1月21日、1月25日分别与2名可疑病例有密切接触，2月3日出现发热等症状，2月7日到莱西市某医院发热门诊就诊并进行隔离治疗。2月8日经青岛市疾控中心核酸检测为阳性，经医院专家组评估，2月9日上午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":9
         }
      },
      {
         "type":"Feature",
         "id":10,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.51393,
               36.85823
            ]
         },
         "properties":{
            "序号Case":50,
            "年龄Age":64,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 08 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"莱西市",
            "地址Address":"青岛市莱西市水集街道办事处前疃村",
            "信息Info":"常住莱西市水集街道办事处前疃村。1月25日、26日曾与2例可疑病例有密切接触史。2月9日通过密接筛查采样送至市疾控中心检测，结果为阳性，属无症状感染者，即转至莱西市某医院就诊并进行隔离治疗。经医院专家组评估，2月9日下午确诊，即转至李沧区某定点医院集中收治。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":10
         }
      },
      {
         "type":"Feature",
         "id":11,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.32289,
               36.079483
            ]
         },
         "properties":{
            "序号Case":51,
            "年龄Age":46,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 07 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 08 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区即墨路街道陵县路",
            "信息Info":"常住市北区即墨路街道陵县路。曾与我市确诊病例33张某某住市北区某医院同一病房住院治疗，病例33张某某确诊后即转至隔离病房治疗，期间2月4日、5日医院两次核酸检测结果均为阴性。2月7日出现憋气、咳嗽、多汗等症状，无发热。2月9日医院再次核酸检测阳性，经医院专家组评估，2月9日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":11
         }
      },
      {
         "type":"Feature",
         "id":12,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.52241,
               36.89541
            ]
         },
         "properties":{
            "序号Case":12,
            "年龄Age":21,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sun, 09 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"李沧区",
            "地址Address":"青岛市莱西市翡翠城西区",
            "信息Info":"常住莱西市翡翠城西区，现租住李沧区虎山路街道虎山花园D区。系我市确诊病例49刘某某的女儿，曾与病例49刘某某有密切接触。2月5日出现轻微干咳症状，2月8日得知其母亲患病后，拨打120至崂山区某医院隔离观察治疗。2月9日经市疾控中心核酸检测结果为阳性，2月9日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":12
         }
      },
      {
         "type":"Feature",
         "id":13,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.373955,
               36.117123
            ]
         },
         "properties":{
            "序号Case":46,
            "年龄Age":43,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区南昌路48号正商红枫谷",
            "信息Info":"现住市北区，系我市确诊病例35的小女儿，1月24日至2月2日白天在病例35所在医院为其陪床，2月4日出现发热等症状，当日到市北区某医院发热门诊就诊，就诊后隔离留观。经市疾控中心检测和专家组评估，2月7日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":13
         }
      },
      {
         "type":"Feature",
         "id":14,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.43067,
               36.180264
            ]
         },
         "properties":{
            "序号Case":2,
            "年龄Age":66,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 19 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 23 Jan 2010 00:00:00 GMT",
            "籍贯_Original":"湖北鄂州",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市李沧区伟东幸福城二期",
            "信息Info":"1月13日赴武汉，1月14日返青，1月16日出现发热症状，1月21日到医院发热门诊就诊。经省、市两级疾病控制中心检测、专家组评估，于1月23日确诊。2月4日治愈出院。追踪排查到密切接触者共36人，已全部解除医学观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":14
         }
      },
      {
         "type":"Feature",
         "id":15,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.04605,
               35.881985
            ]
         },
         "properties":{
            "序号Case":7,
            "年龄Age":54,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 25 Jan 2010 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 00:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"李沧区",
            "地址Address":"青岛市黄岛区隐珠街道欧美世纪花园",
            "信息Info":"现住黄岛区，1月13日到云南旅游，随团接触过2名武汉籍发热患者，1月25日到医院发热门诊就诊。经市疾控中心核酸检测为阳性，1月26日专家组评估确诊。追踪排查到其与病例11、病例12、病例13、病例20密切接触者共109人，已有42人解除医学观察，现有55人正在进行隔离观察，确诊7例，现有疑似5例。（系病例11、病例12的母亲，病例13的岳母，病例20的外婆）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":15
         }
      },
      {
         "type":"Feature",
         "id":16,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.355515,
               36.08344
            ]
         },
         "properties":{
            "序号Case":9,
            "年龄Age":53,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Tue, 26 Jan 2010 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 00:00:00 GMT",
            "籍贯_Original":"湖北武汉",
            "区划_Area_in_Qingdao":"胶州市",
            "地址Address":"青岛市市北区和兴路四季朗廷宾馆",
            "信息Info":"2019年12月12日来青，2020年1月13日起与自武汉抵青的丈夫暂住市北区，1月26日到医院发热门诊就诊。1月26日下午确诊。追踪排查到密切接触者共9人，现有9人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":16
         }
      },
      {
         "type":"Feature",
         "id":17,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.40573,
               36.131386
            ]
         },
         "properties":{
            "序号Case":14,
            "年龄Age":47,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"",
            "初次就诊时间_Diagnose_Date":"Mon, 27 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Thu, 28 Jan 2010 00:00:00 GMT",
            "籍贯_Original":"市北区",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区河西街道德馨筑家小区",
            "信息Info":"市北区人，1月17日从泰国返青，1月27日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，1月28日上午确诊。追踪排查到其与病例24、病例34密切接触者共5人，已有3人解除医学观察，确诊2例。（系病例24的丈夫、病例34的父亲）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":17
         }
      },
      {
         "type":"Feature",
         "id":19,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.42783,
               36.16482
            ]
         },
         "properties":{
            "序号Case":19,
            "年龄Age":7,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Wed, 29 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Thu, 30 Jan 2020 00:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市李沧区南崂路1118号",
            "信息Info":"湖北武汉人，现住李沧区，1月7日自武汉抵达青岛，1月21日到市北区某医院发热门诊就诊，留观隔离治疗。经市疾控中心核酸检测和专家组评估，1月30日上午确诊。追踪排查到密切接触者共8人，已有7人解除医学观察，现有1人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":19
         }
      },
      {
         "type":"Feature",
         "id":22,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.169365,
               36.025867
            ]
         },
         "properties":{
            "序号Case":22,
            "年龄Age":53,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 31 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 01 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区江山北路13号鲁泽观天下",
            "信息Info":"常住黄岛区，1月4日自青岛赴湖北孝感探亲，1月25日回到青岛，1月31日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，2月1日下午确诊。追踪排查到密切接触者共1人，现有1人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":22
         }
      },
      {
         "type":"Feature",
         "id":22,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.153435,
               36.078106
            ]
         },
         "properties":{
            "序号Case":23,
            "年龄Age":46,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sat, 01 Feb 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sun, 02 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区黄岛街道郭家台子村",
            "信息Info":"现住黄岛区，系病例13的姑姑，与病例13有密切接触，2月1日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月2日上午确诊。追踪排查到密切接触者共22人，现有22人正在进行隔离观察。（系病例13的姑姑）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":22
         }
      },
      {
         "type":"Feature",
         "id":24,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87585,
               35.78108
            ]
         },
         "properties":{
            "序号Case":26,
            "年龄Age":39,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 02 Feb 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"黄岛区",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区张家楼镇北寨村",
            "信息Info":"黄岛区人，系病例7的密切接触者，曾与病例7在同一医院就诊。2月2日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，2月3日上午确诊。追踪排查到密切接触者共5人，现有5人正在进行隔离观察。（系病例7的密切接触者）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":24
         }
      },
      {
         "type":"Feature",
         "id":27,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.33269,
               36.077496
            ]
         },
         "properties":{
            "序号Case":27,
            "年龄Age":28,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 02 Feb 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"市北区",
            "区划_Area_in_Qingdao":"市南区",
            "地址Address":"青岛市市北区大连路13号",
            "信息Info":"1月24日参加过亲友聚餐，1月25日出现发热等症状，2月2日到市南区某医院就诊，经预检分诊在发热门诊隔离治疗，2月3日下午确诊。追踪排查到密切接触者共3人，现有2人正在进行隔离观察，确诊1例。（系病例32的孙子、病例33的侄子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":27
         }
      },
      {
         "type":"Feature",
         "id":30,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.34374,
               36.256447
            ]
         },
         "properties":{
            "序号Case":30,
            "年龄Age":20,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 02 Feb 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"城阳区",
            "区划_Area_in_Qingdao":"城阳区",
            "地址Address":"青岛市城阳区卓越蔚蓝群岛小区",
            "信息Info":"在武汉上大学，1月21日从武汉返回青岛，现住城阳区，2月2日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月4日上午确诊。追踪排查到密切接触者共2人，现有2人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":30
         }
      },
      {
         "type":"Feature",
         "id":31,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.33269,
               36.077496
            ]
         },
         "properties":{
            "序号Case":32,
            "年龄Age":85,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Thu, 23 Jan 2020 00:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 00:00:00 GMT",
            "籍贯_Original":"市南区",
            "区划_Area_in_Qingdao":"市南区",
            "地址Address":"青岛市市北区大连路13号",
            "信息Info":"为2月3日确诊病例28岁男性患者的直系亲属，自1月23日起在市南区某医院住院治疗,经市疾控中心核酸检测和专家组评估，2月4日上午确诊。（系病例27的奶奶）于2020年2月8日20时30分抢救无效死亡。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":31
         }
      },
      {
         "type":"Feature",
         "id":32,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.40712,
               36.1329
            ]
         },
         "properties":{
            "序号Case":34,
            "年龄Age":5,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"李沧区",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区合肥路街道德馨筑家小区",
            "信息Info":"系病例14和病例24的儿子，2月4日到李沧区某医院住院治疗。经市疾控中心核酸检测和专家组评估，2月4日下午确诊。与病例14、病例24的共同密切接触者已进行隔离观察。（系病例14和病例24的儿子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":32
         }
      },
      {
         "type":"Feature",
         "id":33,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.30365,
               36.057823
            ]
         },
         "properties":{
            "序号Case":35,
            "年龄Age":71,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市南区云南路街道西康路33号康阳桃源小区",
            "信息Info":"现住市北区，系病例32的密切接触者，曾与病例32居同一病房，2月4日经市疾控中心核酸检测筛查为阳性，即转至李沧区某定点医院进行隔离治疗。经专家组评估，2月5日上午确诊。现已对26名密切接触者开展医学隔离观察。（系病例32的密切接触者、病例39的母亲）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":33
         }
      },
      {
         "type":"Feature",
         "id":34,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.4216,
               36.393085
            ]
         },
         "properties":{
            "序号Case":38,
            "年龄Age":31,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区通济街道世贸商都小区",
            "信息Info":"常住即墨区，系病例29的妹妹、病例31的女儿，2月4日由120运送至即墨区某医院发热门诊就诊，2月5日下午确诊。与病例29、病例31的共同密切接触者已进行隔离观察。（系病例29的妹妹、病例31的女儿）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":34
         }
      },
      {
         "type":"Feature",
         "id":35,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.4216,
               36.393085
            ]
         },
         "properties":{
            "序号Case":37,
            "年龄Age":1,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区通济街道世贸商都小区",
            "信息Info":"现住即墨区，系病例25的外孙、病例36的孙子，2月4日在密切接触者筛查中经市疾控中心核酸检测为阳性，属无症状感染者。2月5日下午由即墨区某医院确诊。与病例25、病例36的共同密切接触者已进行隔离观察。（系病例25的外孙、病例36的孙子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":35
         }
      },
      {
         "type":"Feature",
         "id":39,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.32371,
               36.079926
            ]
         },
         "properties":{
            "序号Case":39,
            "年龄Age":45,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区广东路48号",
            "信息Info":"现住市北区，系病例35的女儿，与病例35有密切接触，2月4日到市北区某医院经预检分诊后到发热门诊就诊，2月5日下午确诊。追踪排查到密切接触者共4人，现有4人正在进行隔离观察。（系病例35的女儿）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":39
         }
      },
      {
         "type":"Feature",
         "id":40,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.30893,
               36.059937
            ]
         },
         "properties":{
            "序号Case":44,
            "年龄Age":48,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Wed, 05 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"李沧区",
            "地址Address":"青岛市市南区云南路街道汶上路6号",
            "信息Info":"现住市南区，为我市确诊病例32和病例35就诊医院的检验科技师，曾接触该院确诊病例的血液标本。2月5日出现发热等症状，2月6日前往李沧区某医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月7日上午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":40
         }
      },
      {
         "type":"Feature",
         "id":45,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.43881,
               36.107834
            ]
         },
         "properties":{
            "序号Case":42,
            "年龄Age":51,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"",
            "是否有其他省份接触史_Being_other_Provinces_":"是",
            "初次就诊时间_Diagnose_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"崂山区",
            "地址Address":"青岛市崂山区金泽人才公寓劲松七路68号",
            "信息Info":"现住崂山区，医务人员。1月19日乘A67107航班由昆明返回青岛（同机乘客中目前已报告多名确诊病例，其中包括我市病例7）。1月25日出现发热症状，自服药1日后恢复。2月5日到市北区某医院发热门诊就诊，经该院核酸检测和专家组评估，2月6日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":45
         }
      },
      {
         "type":"Feature",
         "id":48,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.17848,
               35.958168
            ]
         },
         "properties":{
            "序号Case":47,
            "年龄Age":32,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"是",
            "初次就诊时间_Diagnose_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Fri, 07 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区长江路街道凤凰国际小区",
            "信息Info":"常住黄岛区长江西路157号凤凰国际小区。与其父亲（河南省确诊病例）有密切接触史。1月23日-2月4日，与其父亲在河南濮阳同住。2月5日上午8时左右，与其丈夫、儿子一家三口从河南濮阳自驾车返回黄岛区。2月7日出现发热症状，当日晚前往黄岛区某医院发热门诊就诊。经区疾控中心核酸检测和专家组评估，2月8日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":48
         }
      },
      {
         "type":"Feature",
         "id":50,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.2294,
               35.96365
            ]
         },
         "properties":{
            "序号Case":48,
            "年龄Age":22,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 08 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区嘉陵江东路258号华裕黄金海岸",
            "信息Info":"常住黄岛区嘉陵江东路258号华裕黄金海岸。与我市确诊病例32有密切接触史，系病例32住院期间的护理人员。2月7日区疾控中心对病例32的密切接触者进行采样，2月8日检测为阳性。2月8日出现发热症状，即转至黄岛区某医院发热门诊治疗。经医院专家组评估，2月9日上午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":50
         }
      },
      {
         "type":"Feature",
         "id":54,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.43881,
               36.107834
            ]
         },
         "properties":{
            "序号Case":43,
            "年龄Age":51,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"",
            "是否有其他省份接触史_Being_other_Provinces_":"是",
            "初次就诊时间_Diagnose_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 05 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"崂山区",
            "地址Address":"青岛市崂山区金泽人才公寓劲松七路68号",
            "信息Info":"现住崂山区，医务人员，与病例42系夫妻关系，1月19日与病例42同乘A67107航班由昆明返回青岛。2月5日出现发热症状，当天与病例42一同到市北区某医院发热门诊就诊，经该院核酸检测和专家组评估，2月6日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":54
         }
      },
      {
         "type":"Feature",
         "id":56,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.33172,
               36.07612
            ]
         },
         "properties":{
            "序号Case":45,
            "年龄Age":59,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Thu, 06 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区无棣二路",
            "信息Info":"现住市北区，系我市确诊病例33丈夫的弟弟，因与病例33有密切接触纳入隔离观察。2月7日到崂山区某医院发热门诊就诊，经市疾控中心检测和专家组评估，2月7日下午确诊。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":56
         }
      },
      {
         "type":"Feature",
         "id":57,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.36719,
               36.06962
            ]
         },
         "properties":{
            "序号Case":40,
            "年龄Age":62,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市南区",
            "地址Address":"青岛市市南区晓望路17号",
            "信息Info":"现住市南区，系病例41的丈夫，夫妻二人曾与外市同一确诊病例密切接触，2月5日到市南区某医院就诊，2月5日下午确诊。追踪排查到其与病例41密切接触者共1人，现有1人正在进行隔离观察。（系病例41的丈夫）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":57
         }
      },
      {
         "type":"Feature",
         "id":58,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.36719,
               36.06962
            ]
         },
         "properties":{
            "序号Case":41,
            "年龄Age":62,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"否",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 04 Feb 2020 16:00:00 GMT",
            "籍贯_Original":"",
            "区划_Area_in_Qingdao":"市南区",
            "地址Address":"青岛市市南区晓望路17号",
            "信息Info":"现住市南区，系病例40的妻子，夫妻二人曾与外市同一确诊病例密切接触，2月5日到市南区某医院就诊，2月5日下午确诊。与病例40的共同密切接触者已进行隔离观察。（系病例40的妻子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":58
         }
      },
      {
         "type":"Feature",
         "id":60,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.37194,
               36.0986100000001
            ]
         },
         "properties":{
            "序号Case":1,
            "年龄Age":37,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Thu, 16 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 20 Jan 2010 16:00:00 GMT",
            "籍贯_Original":"湖北武汉",
            "区划_Area_in_Qingdao":"青岛市",
            "地址Address":"青岛市",
            "信息Info":"湖北武汉人，在日照市工作。因发热等症状，于1月17日到日照市就诊，当晚自行至青岛市就诊。经预检分诊了解到其发病前两周内有武汉居住史，立即被收治入院隔离治疗。1月21日，国家卫生健康委诊断专家组确认为山东青岛首例输入性新型冠状病毒感染的肺炎确诊病例。1月29日治愈出院。追踪排查到密切接触者共8人，已全部解除医学观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":60
         }
      },
      {
         "type":"Feature",
         "id":61,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87948,
               35.85866
            ]
         },
         "properties":{
            "序号Case":4,
            "年龄Age":24,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 22 Jan 2010 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 23 Jan 2010 16:00:00 GMT",
            "籍贯_Original":"黄岛区",
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区",
            "信息Info":"1月10日到武汉出差，1月11日返回工作地即墨，1月21日开始发热伴呼吸道症状，1月22日返回黄岛，1月23日到医院发热门诊就诊，医院专家会诊为疑似病例。经市疾控中心核酸检测阳性，1月24日专家组评估确诊。2月4日治愈出院。追踪排查到密切接触者共23人，已有14人解除医学观察，现有8人正在进行隔离观察，现有疑似1例。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":61
         }
      },
      {
         "type":"Feature",
         "id":62,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.33441,
               36.275867
            ]
         },
         "properties":{
            "序号Case":6,
            "年龄Age":56,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 22 Jan 2010 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sun, 24 Jan 2010 16:00:00 GMT",
            "籍贯_Original":"湖北荆门",
            "区划_Area_in_Qingdao":"城阳区",
            "地址Address":"青岛市城阳区",
            "信息Info":"在武汉工作，1月19日离开武汉到莱芜停留1天，1月21日返回莱西，1月24日到医院发热门诊就诊。经市疾控中心核酸检测为阳性，1月25日专家组评估确诊。追踪排查到密切接触者共14人，已有12人解除医学观察，现有2人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":62
         }
      },
      {
         "type":"Feature",
         "id":63,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.36939,
               36.1117
            ]
         },
         "properties":{
            "序号Case":10,
            "年龄Age":44,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":null,
            "初次就诊时间_Diagnose_Date":"Mon, 25 Jan 2010 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 25 Jan 2010 16:00:00 GMT",
            "籍贯_Original":"黑龙江",
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区",
            "信息Info":"1月18日自武汉抵胶州探亲，1月26日到医院发热门诊就诊。1月26日下午确诊。追踪排查到密切接触者共3人，现有3人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":63
         }
      },
      {
         "type":"Feature",
         "id":65,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87948,
               35.85866
            ]
         },
         "properties":{
            "序号Case":11,
            "年龄Age":23,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":null,
            "初次就诊时间_Diagnose_Date":null,
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区",
            "信息Info":"系病例7的二女儿，作为病例7的密切接触者进行医学隔离观察。经市疾控中心核酸检测和专家组评估，1月27日上午确诊，这是我市首起家庭聚集性病例。与病例7、病例12、病例13、病例20的共同密切接触者已进行隔离观察。（系病例7的二女儿、病例12的妹妹）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":65
         }
      },
      {
         "type":"Feature",
         "id":66,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87948,
               35.85866
            ]
         },
         "properties":{
            "序号Case":12,
            "年龄Age":32,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":null,
            "初次就诊时间_Diagnose_Date":null,
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区",
            "信息Info":"系病例7的大女儿，作为病例7的密切接触者进行医学隔离观察。经市疾控中心核酸检测和专家组评估，1月27日上午确诊，这是我市首起家庭聚集性病例。与病例7、病例11、病例13、病例20的共同密切接触者已进行隔离观察。（系病例7的大女儿、病例13的妻子、病例20的母亲、病例23的侄媳）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":66
         }
      },
      {
         "type":"Feature",
         "id":67,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87948,
               35.85866
            ]
         },
         "properties":{
            "序号Case":13,
            "年龄Age":33,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":null,
            "初次就诊时间_Diagnose_Date":null,
            "确诊日期_Confirmed_Date":"Tue, 26 Jan 2010 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区",
            "信息Info":"系病例7的大女婿，作为病例7的密切接触者进行医学隔离观察。经市疾控中心核酸检测和专家组评估，1月27日上午确诊，这是我市首起家庭聚集性病例。与病例7、病例11、病例12、病例20的共同密切接触者已进行隔离观察。（系病例7的大女婿、病例12的丈夫、病例20的父亲、病例23的侄子）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":67
         }
      },
      {
         "type":"Feature",
         "id":68,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.36939,
               36.1117
            ]
         },
         "properties":{
            "序号Case":15,
            "年龄Age":35,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 26 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 27 Jan 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"市北区",
            "地址Address":"青岛市市北区",
            "信息Info":"1月22日和朋友自驾从武汉到济南，1月23日返青，1月27日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，1月28日上午确诊。追踪排查到密切接触者共6人，现有6人正在进行隔离观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":68
         }
      },
      {
         "type":"Feature",
         "id":69,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.943504,
               36.78245
            ]
         },
         "properties":{
            "序号Case":16,
            "年龄Age":42,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sat, 25 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Tue, 28 Jan 2020 16:00:00 GMT",
            "籍贯_Original":"湖北荆州",
            "区划_Area_in_Qingdao":"平度市",
            "地址Address":"青岛市平度市",
            "信息Info":"长期在武汉工作，1月22日从武汉自驾到即墨，1月24日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，1月29日上午确诊。追踪排查到密切接触者共2人，已有2人解除医学观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":69
         }
      },
      {
         "type":"Feature",
         "id":71,
         "geometry":{
            "type":"Point",
            "coordinates":[
               119.87948,
               35.85866
            ]
         },
         "properties":{
            "序号Case":20,
            "年龄Age":7,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Tue, 28 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 29 Jan 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"黄岛区",
            "地址Address":"青岛市黄岛区",
            "信息Info":"现住黄岛区，系病例7的外孙女、病例12和病例13的女儿。1月29日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，1月30日上午确诊。与病例7、病例12、病例13的共同密切接触者已进行隔离观察。（系病例7的外孙女、病例12和病例13的女儿）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":71
         }
      },
      {
         "type":"Feature",
         "id":72,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.52378,
               36.48299
            ]
         },
         "properties":{
            "序号Case":21,
            "年龄Age":35,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":null,
            "初次就诊时间_Diagnose_Date":"Tue, 28 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Wed, 29 Jan 2020 16:00:00 GMT",
            "籍贯_Original":"湖北黄冈",
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区",
            "信息Info":"湖北黄冈人，1月25日自湖北黄冈经江西南昌抵达即墨探亲，1月29日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，1月30日上午确诊。追踪排查到密切接触者共3人，已有3人解除医学观察。",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":72
         }
      },
      {
         "type":"Feature",
         "id":73,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.52378,
               36.48299
            ]
         },
         "properties":{
            "序号Case":25,
            "年龄Age":59,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Fri, 31 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 01 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区",
            "信息Info":"常住即墨区，1月1日前往湖北荆州探亲，1月8日自驾回到即墨，2月1日到医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，2月2日下午确诊。追踪排查到其与病例36、病例37密切接触者共6人，已有4人解除医学观察，确诊2例。（系病例36的亲家、病例37的外婆）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":73
         }
      },
      {
         "type":"Feature",
         "id":74,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.52378,
               36.48299
            ]
         },
         "properties":{
            "序号Case":29,
            "年龄Age":37,
            "性别Gender":"男",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 02 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sun, 02 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区",
            "信息Info":"1月24日由湖北荆州自驾抵青探亲，暂住即墨区，2月3日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月3日下午确诊。追踪排查到其与病例31、病例38密切接触者共8人，已有6人解除医学观察，确诊2例。（系病例31的儿子、病例38的哥哥）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":74
         }
      },
      {
         "type":"Feature",
         "id":75,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.52378,
               36.48299
            ]
         },
         "properties":{
            "序号Case":31,
            "年龄Age":63,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":"是",
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Sun, 02 Feb 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Mon, 03 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"即墨区",
            "地址Address":"青岛市即墨区",
            "信息Info":"系病例29的母亲，1月24日由湖北荆州自驾抵青探亲，现住即墨区，2月3日到医院发热门诊就诊，经市疾控中心核酸检测和专家组评估，2月4日上午确诊。与病例29、病例38的共同密切接触者已进行隔离观察。（系病例29和病例38的母亲）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":75
         }
      },
      {
         "type":"Feature",
         "id":76,
         "geometry":{
            "type":"Point",
            "coordinates":[
               120.40712,
               36.1329
            ]
         },
         "properties":{
            "序号Case":24,
            "年龄Age":36,
            "性别Gender":"女",
            "是否有湖北接触史_Being_to_Hubei_":null,
            "是否有其他省份接触史_Being_other_Provinces_":"否",
            "初次就诊时间_Diagnose_Date":"Mon, 27 Jan 2020 16:00:00 GMT",
            "确诊日期_Confirmed_Date":"Sat, 01 Feb 2020 16:00:00 GMT",
            "籍贯_Original":null,
            "区划_Area_in_Qingdao":"李沧区",
            "地址Address":"青岛市市北区合肥路街道德馨筑家小区",
            "信息Info":"现住市北区，系病例14的妻子，1月28日到李沧区某医院发热门诊就诊。经市疾控中心核酸检测和专家组评估，2月2日上午确诊。与病例14、病例34的共同密切接触者已进行隔离观察。（系病例14的妻子、病例34的母亲）",
            "数据来源Data_Source":"青岛市卫生健康委员会",
            "FID":76
         }
      }
   ]
}